### ISSUE TITLE
使用过程中，连接被拒绝。

### ISSUE THREAD

**Issue by JamesLiu0802** [zhishixiang/tencent-push#1]
![image](https://user-images.githubusercontent.com/86506347/140016359-1ae67dce-7d60-422d-a13a-1c9a99c0e171.png)

**Comment by zhishixiang** [comment]
请同时提供python的后台截图。

**Comment by JamesLiu0802** [comment]
![image](https://user-images.githubusercontent.com/86506347/140605279-bd0690a5-84a3-4fee-80cd-d8fcaddb348f.png)

**Comment by zhishixiang** [comment]
> ![image](https://user-images.githubusercontent.com/86506347/140605279-bd0690a5-84a3-4fee-80cd-d8fcaddb348f.png)
> 

gocqhttp还是显示无法连接吗

**Comment by JamesLiu0802** [comment]
![image](https://user-images.githubusercontent.com/86506347/140605330-4354fdcf-f57e-488f-8858-86ab8e5a0275.png)
是的，还是这样

**Comment by JamesLiu0802** [comment]
python3.9，路径是home/push

**Comment by zhishixiang** [comment]
> ![image](https://user-images.githubusercontent.com/86506347/140605330-4354fdcf-f57e-488f-8858-86ab8e5a0275.png)
> 是的，还是这样

你可以看看什么程序占用了8080端口，可能是你多开了一个python脚本没来得及关闭

**Comment by zhishixiang** [comment]
> python3.9，路径是home/push

不是这个，你lsof -i:8080看看

**Comment by JamesLiu0802** [comment]
![image](https://user-images.githubusercontent.com/86506347/140605475-b7852042-6581-471a-9275-f28c0b8da002.png)

**Comment by JamesLiu0802** [comment]
![image](https://user-images.githubusercontent.com/86506347/140605499-20cb5f4b-1a1c-4d92-ab6e-d8197013eba3.png)
我的系统是centos7.9

**Comment by JamesLiu0802** [comment]
![image](https://user-images.githubusercontent.com/86506347/140605633-afedeec9-1b0a-41da-a81a-c47afc9809fc.png)

**Comment by zhishixiang** [comment]
> ![image](https://user-images.githubusercontent.com/86506347/140605633-afedeec9-1b0a-41da-a81a-c47afc9809fc.png)
> 

这个我以前也看到有人出现过，换python3.8.3就好了，我现在用的框架兼容性不怎么好，打算以后重写一遍。

**Comment by Penghaiku** [comment]
同样遇到这个问题
